name: rddpred_predictrdds 
description:  
keywords:
    - machine learning 
    - RNA-editing 
tools:
    - rddpred:
        description: |
            rddpred 
        homepage: http://epigenomics.snu.ac.kr/RDDpred/ 
        documentation: http://epigenomics.snu.ac.kr/RDDpred/manual.php 
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
            List of input FastQ files of size 1 and 2 for single-end and paired-end data,
            respectively.
    - index:
      type: directory
      description: STAR genome index
      pattern: "star"
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Output BAM file containing read alignments
        pattern: "*.{bam}"
    - log_final:
        type: file
        description: STAR final log file
        pattern: "*Log.final.out"
    - log_out:
        type: file
        description: STAR lot out file
        pattern: "*Log.out"
    - log_progress:
        type: file
        description: STAR log progress file
        pattern: "*Log.progress.out"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
  - bam_sorted:
        type: file
        description: Sorted BAM file of read alignments (optional)
        pattern: "*sortedByCoord.out.bam"
  - bam_transcript:
        type: file
        description: Output BAM file of transcriptome alignment (optional)
        pattern: "*toTranscriptome.out.bam"
  - bam_unsorted:
        type: file
        description: Unsorted BAM file of read alignments (optional)
        pattern: "*Aligned.unsort.out.bam"
  - fastq:
        type: file
        description: Unmapped FastQ files (optional)
        pattern: "*fastq.gz"
  - tab:
        type: file
        description: STAR output tab file(s) (optional)
        pattern: "*.tab"
authors:
    - "@abotzki
